version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  redis:
    image: "redis"
    container_name: "my_redis"
    ports:
      - "6379:6379"
volumes:
  my_dbdata: