# Generated by Django 2.0.3 on 2018-05-30 18:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('frueringcontent', '0004_auto_20180529_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('article', wagtail.core.blocks.StructBlock([('banner_image', wagtail.images.blocks.ImageChooserBlock()), ('article_title', wagtail.core.blocks.CharBlock(required=True)), ('article_body', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(template='frueringcontent/article/article_image.html')), ('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock(template='frueringcontent/article/article_image.html'))]))]))]),
        ),
    ]
