# Generated by Django 2.0.3 on 2018-05-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='featured_image',
            new_name='_featured_image',
        ),
    ]
