# Generated by Django 2.0.3 on 2018-06-11 19:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpage_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='title', template='frueringcontent/article/blocks/article_header_block.html')), ('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link'], template='frueringcontent/article/blocks/article_text_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock(template='frueringcontent/article/blocks/article_image_block.html')), ('banner_image', wagtail.images.blocks.ImageChooserBlock(template='frueringcontent/article/blocks/article_banner_image_block.html'))], blank=True),
        ),
    ]
