# Generated by Django 2.0.3 on 2018-05-13 11:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180507_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField((('blogroll', wagtail.core.blocks.StructBlock((('block_title', wagtail.core.blocks.CharBlock(max_length=80, required=True)), ('blog_page', wagtail.core.blocks.PageChooserBlock(target_model=['blog.BlogIndexPage']))))),)),
        ),
    ]
