# Generated by Django 2.0.3 on 2018-05-29 19:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180523_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('blogroll', wagtail.core.blocks.StructBlock([('block_title', wagtail.core.blocks.CharBlock(max_length=80, required=True)), ('blog_page', wagtail.core.blocks.PageChooserBlock(target_model=['blog.BlogIndexPage']))])), ('richtext_article', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))], template='fruering/blocks/richtext_article_block.html'))]),
        ),
    ]
