# Generated by Django 2.0.3 on 2018-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formemailpage',
            name='form_section_header',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='formemailpage',
            name='submit_button_text',
            field=models.CharField(default='Send', max_length=50),
        ),
    ]
