# Generated by Django 2.0.3 on 2018-06-08 18:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0002_auto_20180521_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formemailpage',
            name='form_section_header',
        ),
        migrations.RemoveField(
            model_name='formemailpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='formemailpage',
            name='form_body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='frueringcontent/article/blocks/article_image_block.html')), ('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link'], template='frueringcontent/article/blocks/article_text_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock(template='frueringcontent/article/blocks/article_image_block.html'))], blank=True),
        ),
    ]
