# Generated by Django 2.0.3 on 2018-06-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('formbuilder', '0007_auto_20180611_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='formemailpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
